### ISSUE TITLE
uwsim Communication

### ISSUE THREAD

**Issue by HeadReaper-hc** [pengzhi1998/Underwater-obstacle-avoidance#2]
Hello, do you use uwsim? I have some questions, can I Communicate with you?

**Comment by pengzhi1998** [comment]
Yes I do. Of course! I'm fresh one on UWsim as well. But we could discuss it. My email is tyypz2590477658@gmail.com.

**Comment by HeadReaper-hc** [comment]
老哥，我看你简介是国人啊，我微信hchao_xs，有兴趣咱可以交流一下
